using System.Runtime.InteropServices;

namespace WhiteMagic.WinAPI.Structures
{
    /// <summary>
    ///     Contains information about a simulated message generated by an input device other than a keyboard or mouse.
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    public struct HardwareInput
    {
        /// <summary>
        ///     The message generated by the input hardware.
        /// </summary>
        public int Message;

        /// <summary>
        ///     The low-order word of the lParam parameter for <see cref="Message" />.
        /// </summary>
        public short WParamL;

        /// <summary>
        ///     The high-order word of the lParam parameter for <see cref="Message" />.
        /// </summary>
        public short WParamH;
    }
}